from pptx import Presentation
import os
import random
import time

def create_powerpoint_file(topic, slide_data, output_folder):
    # Load configurations
    TEMPLATE_FILE = os.getenv("TEMPLATE_FILE")
    TITLE_TEMPLATE_SLIDE_INDEX = int(os.getenv("TITLE_TEMPLATE_SLIDE_INDEX"))
    CONTENT_TEMPLATE_SLIDE_INDEX = int(os.getenv("CONTENT_TEMPLATE_SLIDE_INDEX"))
    
    # Load the template
    prs = Presentation(TEMPLATE_FILE)

    # Add title slide
    slide_layout = prs.slide_layouts[TITLE_TEMPLATE_SLIDE_INDEX]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = topic
    subtitle.text = "Generated by SkyDock.ai"
    
    # Add content slides
    for slide_content in slide_data:
        new_slide = prs.slides.add_slide(prs.slide_layouts[CONTENT_TEMPLATE_SLIDE_INDEX])
        new_slide.shapes.title.text = slide_content["title"]
        new_slide.placeholders[1].text = "\n".join(slide_content["content"])
    
    # Save the presentation
    output_file_path = f'{output_folder}/{generate_random_file_name()}.pptx'
    prs.save(output_file_path)
    return output_file_path

def generate_random_file_name():
    return f'{int(time.time_ns())}_{random.randint(0,10000)}'